services:
# Backend szolgáltatás (már meglévő)
  - type: web
    name: fastapi-backend
    runtime: docker
    repo: https://github.com/aszilagyi1989/AskAIwithPyReactFastapi
    dockerContext: backend
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: PORT
        value: 10000


# Frontend szolgáltatás (új)
  - type: web
    name: react-frontend
    runtime: docker
    dockerContext: frontend
    dockerfilePath: frontend/Dockerfile
    envVars:
      - key: VITE_API_URL
        value: https://askaiwithpyreactfastapibackend.onrender.com